package ganguo.oven.bluetooth;

/**
 * Created by Tony on 1/18/15.
 */
public enum BleCommand {
    SCAN_START, SCAN_STOP, SCAN_FOUND, CONNECT, CONNECTED, DISCONNECTED, SERVICES_DISCOVERED, NOTIFY, NOTIFY_RECEIVE_DATA,
    SETTING_COMMAND, START_RECODE, STOP_RECODE, PROBE_TEMPERATURE_CHANGE, CONNECT_ERROR,START_SCAN_THREAD
}
